name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: arduino-cli compile --fqbn SeeedJP:nrf52:wio_bg770a ./sample
      - name: upload
        run: |
          #  ボーレート1200でつなぐことでDFUモードに入る
          mode COM3: BAUD=1200
          arduino-cli -p com4 upload --fqbn SeeedJP:nrf52:wio_bg770a ./sample
        shell: pwsh
      - name: monitor
        run: |
          $job = Start-Job -ScriptBlock {
              $process = Start-Process "arduino-cli" -ArgumentList "-p com3 monitor" -PassThru
              $process.StandardOutput.BaseStream.CopyTo([System.IO.File]::Create("output.log"))
              $process.WaitForExit()
          }
          Start-Sleep -Seconds 10
          Stop-Job -Job $job
          Remove-Job -Job $job
          Get-Content "output.log" 
        shell: pwsh
          