name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: build
        run: arduino-cli compile --fqbn SeeedJP:nrf52:wio_bg770a ./sample
      - name: upload
        run: |
          #  ボーレート1200でつなぐことでDFUモードに入る
          # mode COM3: BAUD=1200
          # またはボードの定義を変更し、com3とcom4で2回uploadを呼び出す
          # BG770Aの場合は以下のように変更
          # tools.nrfutil.upload.pattern="{cmd}" {upload.verbose} dfu serial -pkg "{build.path}/{build.project_name}.zip" -p {serial.port} -b 115200 --singlebank -t 1200
          # (-t 1200を追加)
          arduino-cli -p com3 upload --fqbn SeeedJP:nrf52:wio_bg770a ./sample
          arduino-cli -p com4 upload --fqbn SeeedJP:nrf52:wio_bg770a ./sample
        shell: pwsh
      - name: monitor
        run: |
          arduino-cli board list
          $process = Start-Process cmd.exe -ArgumentList "/c arduino-cli monitor -p com3 --fqbn SeeedJP:nrf52:wio_bg770a --raw --log-level trace --log > output.log"
          Start-Sleep -Seconds 20
          if (!$process.HasExited) {
            Stop-Process -Id $process.Id
          }
          Get-Content "output.log" 
        shell: pwsh
          